### ISSUE TITLE
`.sty` files instead of `.tex`?

### ISSUE THREAD

**Issue by kellertuer** [mossr/julia-mono-listings#6]
Great approach – I am always looking for a nice and easy way to get my Julia code nice and tidy in my TeX files :)

I have a short remark: There is also https://github.com/wg030/jlcode, but it does not use Julia Mono (but defines a lot of utf8 helpers)

And I have a question: Have you thought about changing the `.tex` files to `.sty` files? Then you could use `\usepackage` instead of an `\input` and one could even work towards package options?

**Comment by mossr** [comment]
Glad you're enjoying this! I really like the `.sty` idea—if anyone would like to submit a PR I'd be happy to review.

**Comment by kellertuer** [comment]
Sure, I know how that can be done. If I find time, I could provide such a PR.
